apiVersion: v1
kind: Service
metadata:
  name: {{.Values.fraudMlService.service.name}}
  labels:
    app: {{.Values.fraudMlService.app.name}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.fraudMlService.app.name}}
  ports:
    - name: http
      port: {{ .Values.fraudMlService.port }}
      targetPort: {{ .Values.fraudMlService.port }}
