apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.orderApi.service.name }}
  labels:
    app: {{.Values.orderApi.app.name}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.orderApi.app.name}}
  ports:
    - name: http
      port: {{ .Values.orderApi.port }}
      targetPort: {{ .Values.orderApi.port }}
