apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.paymentWorker.secretConfig.name}}
type: Opaque
stringData:
{{- range $k, $v := .Values.paymentWorker.secrets }}
  {{ $k }}: "{{ $v }}"
{{- end }}
