basePath: /api/v1
definitions:
  views.OrderRequest:
    description: Order request info
    properties:
      accountId:
        type: string
      amount:
        maximum: 5000
        type: number
      currency:
        enum:
        - USD
        - CAD
        type: string
      idempotencyId:
        description: Client-provided UUID for idempotency
        type: string
    required:
    - accountId
    - amount
    - currency
    - idempotencyId
    type: object
host: localhost:8000
info:
  contact:
    url: https://github.com/nimeshabuddhika
  description: 'User UUID for demo authentication (TODO: replace with JWT)'
  license:
    name: MIT License
  title: Order API
  version: "1.0"
paths:
  /orders:
    post:
      consumes:
      - application/json
      description: 'Creates an order and publishes to Kafka if valid. The userId in
        the header is for demo only (TODO: replace with JWT)'
      parameters:
      - description: User UUID
        in: header
        name: userId
        required: true
        type: string
      - description: Order details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/views.OrderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Order created
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create a new order
      tags:
      - orders
schemes:
- http
swagger: "2.0"
