# Configuration for Order API
# For local development only

PORT: "8081"
AES_KEY: "Zk6IWX04Qm7ThZ5dJi8Xo4zyb8g9wfcxr5jxa1i3JKU=" # For local development only
KAFKA_ORDER_TOPIC: "orders-placed"
KAFKA_ORDER_RETENTION: "24h"
KAFKA_BROKERS: "localhost:9092"
PRIMARY_DB_ADDR: "db_user:db_password@localhost:6432/resilient_payment_processor?sslmode=disable" # For local development only
READ_DB_ADDR: "db_user:db_password@localhost:6433/resilient_payment_processor?sslmode=disable" # For local development only
GIN_MODE: "debug"