apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: {{ .Values.grafana.admin.username | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.grafana.admin.password | quote }}
