apiVersion: v1
kind: Service
metadata:
  name: {{.Values.grafana.service.name}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.grafana.app.name}}
  ports:
    - name: http
      port: {{.Values.grafana.service.port}}
      targetPort: {{.Values.grafana.service.port}}