apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.loki.pvc.name}}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size.loki }}