apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: infra
data:
  promtail.yaml: |
    server:
      log_level: info
      log_format: logfmt
      http_listen_port: 9080
      grpc_listen_port: 0

    clients:
      - url: http://loki-service:3100/loki/api/v1/push

    positions:
      filename: /run/promtail/positions.yaml

    scrape_configs:
      - job_name: kubernetes-pods
        pipeline_stages:
          - cri: {}

        kubernetes_sd_configs:
          - role: pod

        relabel_configs:
          # Basic useful labels
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace

          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

          - action: replace
            source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container

          - action: replace
            source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node_name

          # ONE SIMPLE PATH: read all container logs from this node
          - action: replace
            target_label: __path__
            replacement: /var/log/pods/*$1/*.log
      - job_name: pods-static
        static_configs:
          - targets:
              - localhost
            labels:
              job: pods-static
              __path__: /var/log/pods/*/*/*.log