apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /run/promtail/positions.yaml
    clients:
      - url: http://loki-service:3100/loki/api/v1/push
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        # Keep only pods that have label: logging=promtail
        relabel_configs:
          - action: keep
            source_labels: [ __meta_kubernetes_pod_label_logging ]
            regex: promtail
          # Useful context labels
          - action: replace
            source_labels: [ __meta_kubernetes_namespace ]
            target_label: namespace
          - action: replace
            source_labels: [ __meta_kubernetes_pod_name ]
            target_label: pod
          - action: replace
            source_labels: [ __meta_kubernetes_pod_container_name ]
            target_label: container
          - action: replace
            source_labels: [ __meta_kubernetes_node_name ]
            target_label: node
          # Point Promtail at the CRI log files for the container
          - action: replace
            replacement: /var/log/pods/*/*/*.log
            target_label: __path__
        pipeline_stages:
          # Parse CRI log format (containerd/CRI-O)
          - cri: { }
          # If app logs JSON and contains a "level" field
          - json:
              expressions:
                level: level
            # Only adds the label if the JSON field exists
          - labels:
              level: