apiVersion: v1
kind: Service
metadata:
    name: {{.Values.prometheus.service.name}}
spec:
    type: ClusterIP
    selector:
        app: {{.Values.prometheus.app.name}}
    ports:
        - name: http
          port: {{.Values.prometheus.service.port}}
          targetPort: {{.Values.prometheus.port}}