apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.prometheus.storageClassName }}
  storageClassName: {{ .Values.prometheus.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size.prometheus }}
