{{- if .Values.service.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: infra
spec:
  type: NodePort
  selector: { app: kafka }
  ports:
    - name: external
      port: 9092
      targetPort: external
      nodePort: {{ .Values.service.external.nodePort }}
{{- end }}
