apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: infra
spec:
  type: {{ .Values.service.type }}
  selector: { app: kafka-ui }
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: http
