namespace: db
nodeSelector:
  rpp: db

images:
  postgres: postgres:17.5
  haproxy: haproxy:3.2
  pgbouncer: edoburu/pgbouncer:v1.24.1-p1

storage:
  className: ""        # e.g., "local-path" on k3d, or leave empty to use cluster default
  primarySize: 10Gi
  replicaSize: 10Gi

serviceTypes:
  postgresPrimary: NodePort
  haproxy: NodePort
  pgbouncerWrite: NodePort
  pgbouncerRead: NodePort

nodePorts:   # set to null to let k8s allocate
  postgresPrimary: 30032   # maps to container 5432 (write primary)
  haproxy: 30040           # maps to container 5432 (reads via HAProxy)
  pgbouncerWrite: 30432    # maps to container 6432
  pgbouncerRead: 30433     # maps to container 6432

postgres:
  dbName: resilient_payment_processor
  appUser: db_user
  appPassword: db_password         # for dev only; override via --set or external Secret in real envs
  replUser: repl_user
  replPassword: repl_password
  primary:
    resources: {}
    extraEnv:
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=trust"
    # Optional: pass custom *.sql/*.sh via values.files to /docker-entrypoint-initdb.d
    additionalInitFiles: []  # each item: { name: "filename.sql", content: |-"SQL here" }
  replicas:
    - name: replica-1
      slot: slot_replica_1
      resources: {}
    - name: replica-2
      slot: slot_replica_2
      resources: {}

haproxy:
  resources: {}
  config: |
    global
      maxconn 5000
      log stdout format raw daemon
    defaults
      log global
      mode tcp
      timeout connect 5s
      timeout client  1m
      timeout server  1m
    frontend pg_read
      bind *:5432
      default_backend replicas
    backend replicas
      balance roundrobin
      option tcp-check
      default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
      server r1 postgres-replica-1:5432 check
      server r2 postgres-replica-2:5432 check

pgbouncer:
  write:
    resources: {}
    ini: |
      [databases]
      {{ .Values.postgres.dbName }} = host=postgres-primary port=5432 
      [pgbouncer]
      listen_addr = 0.0.0.0
      listen_port = 6432
      auth_type = scram-sha-256
      auth_file = /etc/pgbouncer/userlist.txt
      pool_mode = transaction
      max_client_conn = 1000
      default_pool_size = 50
      server_tls_sslmode = disable
  read:
    resources: {}
    ini: |
      [databases]
      {{ .Values.postgres.dbName }} = host=haproxy-read port=5432
      [pgbouncer]
      listen_addr = 0.0.0.0
      listen_port = 6432
      auth_type = scram-sha-256
      auth_file = /etc/pgbouncer/userlist.txt
      pool_mode = transaction
      max_client_conn = 1000
      default_pool_size = 50
      server_tls_sslmode = disable
  userlist: |
    "db_user" "db_password"

probes:
  pgReadyCmd: ["sh","-c","pg_isready -U {{ .Values.postgres.appUser }} -d {{ .Values.postgres.dbName }}"]

