nodeSelector:
  rpp: apps

imagePullPolicy: Always
imagePullSecrets: []  # e.g., [{ name: "rpp-registry" }]

resources: {}  # set per container e.g. (limits/requests)

orderApi:
  replicas: 1
  image: "rpp-registry:5000/order-api:dev"
  port: 8081
  labels:
    logging: "promtail"
  configmap:
    name: "order-api-config"
  secretConfig:
    name: "order-api-secret"
  app:
    name: "order-api"
  service:
    name: "order-api-svc"
  env:
    GIN_MODE: "release"
    APP_PORT: "8081"
    APP_KAFKA_BROKERS: "kafka.infra.svc.cluster.local:29092"
    APP_KAFKA_ORDER_TOPIC: "orders-placed"
    APP_KAFKA_ORDER_RETENTION: "24h"
    APP_MAX_DB_CONNECTIONS: "50"
    APP_MIN_DB_CONNECTIONS: "5"
  secrets:
    APP_AES_KEY: "Zk6IWX04Qm7ThZ5dJi8Xo4zyb8g9wfcxr5jxa1i3JKU="
    APP_PRIMARY_DB_ADDR: "db_user:db_password@pgbouncer-write.db.svc.cluster.local:6432/resilient_payment_processor?sslmode=disable"
    APP_READ_DB_ADDR: "db_user:db_password@pgbouncer-read.db.svc.cluster.local:6432/resilient_payment_processor?sslmode=disable"
  ingress:
    name: "order-api-ingress"
    enabled: true
    className: traefik
    host: "order-api.localtest.me"
    path: "/"
    tls:
      enabled: false
      secretName: "order-api-tls"
  # Prometheus annotation scrape via service
  metrics:
    enabled: true
    name: "order-api-metrics-svc"
    path: "/metrics"
    scheme: "http"

paymentWorker:
  replicas: 1
  image: "rpp-registry:5000/payment-worker:dev"
  labels:
    logging: "promtail"
  configmap:
    name: "payment-worker-config"
  secretConfig:
    name: "payment-worker-secret"
  app:
    name: "payment-worker"
  env:
    GIN_MODE: "release"
    APP_METRICS_ADDR: ":2112"
    APP_KAFKA_BROKERS: "kafka.infra.svc.cluster.local:29092"
    APP_KAFKA_ORDER_TOPIC: "orders-placed"
    APP_KAFKA_DLQ_TOPIC: "orders-placed-dlq"
    APP_KAFKA_DLQ_RETENTION: "48h"
    APP_KAFKA_RETRY_TOPIC: "orders-retry"
    APP_KAFKA_RETRY_RETENTION: "48h"
    APP_KAFKA_RETRY_DLQ_TOPIC: "orders-retry-dlq"
    APP_KAFKA_RETRY_DLQ_RETENTION: "168h"
    APP_KAFKA_ORDER_CONSUMER_GROUP: "payment-order-workers"
    APP_KAFKA_RETRY_CONSUMER_GROUP: "payment-retry-workers"
    APP_MAX_DB_CONNECTIONS: "50"
    APP_MIN_DB_CONNECTIONS: "5"
    APP_REDIS_ADDR: "redis.infra.svc.cluster.local:6379"
    APP_RETRY_BASE_BACKOFF: "30s"
    APP_MAX_RETRY_BACKOFF: "5m"
    APP_MAX_RETRY_COUNT: "3"
    APP_MAX_ORDERS_PLACED_CONCURRENT_JOBS: "1000"
    APP_MAX_ORDERS_RETRY_CONCURRENT_JOBS: "1000"
    APP_FRAUD_ML_SERVICE_ADDR: "http://fraud-ml-svc:8082"
    APP_ML_RATE_LIMIT_PER_SEC: "1000"
    APP_ML_REQUEST_BURST: "60"
    APP_ML_REQUEST_MAX_THROTTLE_WAIT: "1s"
  secrets:
    APP_AES_KEY: "Zk6IWX04Qm7ThZ5dJi8Xo4zyb8g9wfcxr5jxa1i3JKU="
    APP_PRIMARY_DB_ADDR: "db_user:db_password@pgbouncer-write.db.svc.cluster.local:6432/resilient_payment_processor?sslmode=disable"
    APP_READ_DB_ADDR: "db_user:db_password@pgbouncer-read.db.svc.cluster.local:6432/resilient_payment_processor?sslmode=disable"
  # Prometheus annotation scrape via service
  metrics:
    enabled: true
    name: "payment-worker-metrics-svc"
    port: 2112
    path: "/metrics"
    scheme: "http"

fraudMlService:
  replicas: 1
  image: "rpp-registry:5000/fraud-ml-service:dev"
  port: 8082
  app:
    name: "fraud-ml-service"
  configmap:
    name: "fraud-ml-service-config"
  service:
    name: "fraud-ml-svc"
  env:
    MODEL_PATH: "/app/train/fraud_model.onnx"
    FRAUD_THRESHOLD: "0.5"
    PORT: "8082"
  ingress:
    name: "fraud-ml-service-ingress"
    enabled: true
    className: traefik
    host: "fraud-ml-service.localtest.me"
    path: "/"
    tls:
      enabled: false
      secretName: "fraud-ml-service-tls"
  # Prometheus annotation scrape via service
  metrics:
    enabled: true
    name: "fraud-ml-service-metrics-svc"
    path: "/metrics"
    scheme: "http"