namespace: infra

nodeSelector:
  rpp: infra

storageClassName: ""   # empty -> default storage class (e.g., local-path on k3d)
persistence:
  size:
    prometheus: 10Gi
    grafana: 5Gi
    loki: 10Gi

prometheus:
  image: prom/prometheus:v3.7.2
  port: 9090
  service:
    name: "prometheus-svc"
    port: 9090
  app:
    name: "prometheus"
  storageClassName: ""
  configMap:
    name: prometheus-config
    key: prometheus.yml
  extraArgs:
    - --web.enable-lifecycle
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
  ingress:
    name: "prometheus-ingress"
    enabled: true
    className: traefik
    host: "prometheus.localtest.me"
    path: "/"
    tls:
      enabled: false
      secretName: "prometheus-tls"


grafana:
  image: grafana/grafana:12.2
  app:
    name: "grafana"
  admin:
    username: admin
    password: admin   # local/dev only
  service:
    name: "grafana-service"
    port: 3000
  ingress:
    name: "grafana-ingress"
    enabled: true
    className: traefik
    host: "grafana.localtest.me"
    path: "/"
    tls:
      enabled: false
      secretName: "grafana-tls"

loki:
  image: grafana/loki:3.5.0
  port: 3100
  app:
    name: "loki"
  service:
    name: "loki-service"
    type: ClusterIP
  pvc: # Persistent Volume Claim
    name: "loki-data"

promtail:
  image: grafana/promtail:3.5.0
  resources: {}
