apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.dbName | quote }}
  POSTGRES_USER: {{ .Values.postgres.appUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.appPassword | quote }}
  REPL_USER: {{ .Values.postgres.replUser | quote }}
  REPL_PASSWORD: {{ .Values.postgres.replPassword | quote }}
