apiVersion: v1
kind: Secret
metadata:
  name: postgres-init-sql
type: Opaque
stringData:
  00-init.sql: |
    DO $$ BEGIN
      PERFORM 1 FROM pg_database WHERE datname = '{{ .Values.postgres.dbName }}';
      IF NOT FOUND THEN
        CREATE DATABASE {{ .Values.postgres.dbName }};
      END IF;
    END $$;

    DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{{ .Values.postgres.appUser }}') THEN
        CREATE USER {{ .Values.postgres.appUser }} WITH ENCRYPTED PASSWORD '{{ .Values.postgres.appPassword }}';
      END IF;
    END $$;

    DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{{ .Values.postgres.replUser }}') THEN
        CREATE ROLE {{ .Values.postgres.replUser }} WITH REPLICATION LOGIN PASSWORD '{{ .Values.postgres.replPassword }}';
      END IF;
    END $$;

    CREATE SCHEMA IF NOT EXISTS svc_schema;
    ALTER DATABASE resilient_payment_processor SET search_path = svc_schema;

    SELECT pg_create_physical_replication_slot('{{ (index .Values.postgres.replicas 0).slot }}') ON CONFLICT DO NOTHING;
    SELECT pg_create_physical_replication_slot('{{ (index .Values.postgres.replicas 1).slot }}') ON CONFLICT DO NOTHING;

  {{- range .Values.postgres.primary.additionalInitFiles }}
  {{ .name }}: |-
{{ .content | indent 4 }}
  {{- end }}
