apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-read
spec:
  type: {{ .Values.serviceTypes.pgbouncerRead }}
  selector: { app: pgbouncer-read }
  ports:
    - name: pgb
      port: 6432
      targetPort: 6432
      {{- if .Values.nodePorts.pgbouncerRead }}
      nodePort: {{ .Values.nodePorts.pgbouncerRead }}
      {{- end }}
