apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-write
spec:
  type: {{ .Values.serviceTypes.pgbouncerWrite }}
  selector: { app: pgbouncer-write }
  ports:
    - name: pgb
      port: 6432
      targetPort: 6432
      {{- if .Values.nodePorts.pgbouncerWrite }}
      nodePort: {{ .Values.nodePorts.pgbouncerWrite }}
      {{- end }}
