apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
spec:
  type: {{ .Values.serviceTypes.postgresPrimary }}
  selector:
    app: postgres-primary
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
      {{- if .Values.nodePorts.postgresPrimary }}
      nodePort: {{ .Values.nodePorts.postgresPrimary }}
      {{- end }}
