CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     username VARCHAR(255) UNIQUE NOT NULL,
                                     created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                     updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS accounts (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
                                        balance DECIMAL(15, 2) NOT NULL DEFAULT 0.00, -- TODO be encrypted
                                        currency VARCHAR(3) NOT NULL DEFAULT 'CAD',
                                        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                        updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
                                      account_id BIGINT REFERENCES accounts(id) ON DELETE CASCADE,
                                      idempotency_key  UUID NOT NULL,
                                      amount DECIMAL(15, 2) NOT NULL,
                                      status VARCHAR(50) NOT NULL DEFAULT 'pending', -- e.g., pending, processed, failed.
                                      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for scalability (e.g., Kafka partitioning by user_id).
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_accounts_user_id ON accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_accounts_idempotency_key ON orders(idempotency_key);