
# Configuration for User API Seed
# For local development only

PRIMARY_DB_ADDR: "db_user:db_password@localhost:6432/resilient_payment_processor?sslmode=disable" # For local development only
READ_DB_ADDR: "db_user:db_password@localhost:6433/resilient_payment_processor?sslmode=disable" # For local development only
AES_KEY: "Zk6IWX04Qm7ThZ5dJi8Xo4zyb8g9wfcxr5jxa1i3JKU=" # For local development only
MAX_DB_CONNECTIONS: 10
MIN_DB_CONNECTIONS: 2
