{
 "title": "Payment Worker - Loki",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Payment-worker logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"^resilient-payment-processor-payment-worker-.*\"} | json | msg = `payment_processed_successfully`"
    }
   ]
  },
  {
   "title": "Order success By Range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (msg) (count_over_time({service_name=~\"^resilient-payment-processor-payment-worker-.*\"} | json | msg = `order_commited_successfully`[$__range]))"
    },
    {
     "direction": "backward",
     "expr": "sum by (msg) (count_over_time({service_name=~\"^resilient-payment-processor-payment-worker-.*\"} | json | msg = `order_failed_to_commit`[$__range]))"
    },
    {
     "direction": "backward",
     "expr": "sum by (msg) (count_over_time({service_name=~\"^resilient-payment-processor-payment-worker-.*\"} | json | msg = `payment_processed_successfully`[$__range]))"
    }
   ]
  },
  {
   "title": "Payment Worker - Order Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (msg) (count_over_time({service_name=~\"^resilient-payment-processor-payment-worker-.*\"} | json | msg = `processing_payment_job`[$__range]))"
    },
    {
     "direction": "backward",
     "expr": "sum by (msg) (count_over_time({service_name=~\"^resilient-payment-processor-payment-worker-.*\"} | json | msg = `payment_processed_successfully`[$__range]))"
    },
    {
     "direction": "backward",
     "expr": "sum by (msg) (count_over_time({service_name=~\"^resilient-payment-processor-payment-worker-.*\"} | json | msg = `process_payment_failed_sending_to_dlq`[$__range]))"
    },
    {
     "direction": "backward",
     "expr": "sum by (msg) (count_over_time({service_name=~\"^resilient-payment-processor-payment-worker-.*\"} | json | msg = `order_commited_successfully`[1m]) )",
     "legendFormat": "msg"
    },
    {
     "direction": "backward",
     "expr": "sum by(msg)  (count_over_time({service_name=~\"^resilient-payment-processor-payment-worker-.*\"} | json | caller =~ \"^services/kafka_order_handler.*\" | msg = `order_failed_to_commit`[1m]) )"
    }
   ]
  },
  {
   "title": "order-api",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"order-api\"} | json | level != \"\""
    }
   ]
  }
 ]
}