apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels: { app: kafka }
spec:
  clusterIP: None
  selector: { app: kafka }
  ports:
    - name: broker-internal
      port: 29092
      targetPort: 29092
    - name: controller
      port: 29093
      targetPort: 29093